### ISSUE TITLE
Add description of what is Tech Phantoms

### ISSUE THREAD

**Issue by Panquesito7** [Tech-Phantoms/.github#7]
If we add what Tech Phantoms is about, its website, its socials, etc., it would attract more users to
engage with the community. If you tell me a bit of what Tech Phantoms is, I could write something for it.

Let me know what do you think. Thanks. 🙂

**Comment by imabp** [comment]
I guess, we already have added our twitter and LinkedIn, and that's good right !!:)..
If yes, please close this issue.
